[2025-07-06T15:00:18.336+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world.hello_file_task manual__2025-07-06T15:00:16.458026+00:00 [queued]>
[2025-07-06T15:00:18.341+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world.hello_file_task manual__2025-07-06T15:00:16.458026+00:00 [queued]>
[2025-07-06T15:00:18.342+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-07-06T15:00:18.353+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): hello_file_task> on 2025-07-06 15:00:16.458026+00:00
[2025-07-06T15:00:18.362+0000] {standard_task_runner.py:57} INFO - Started process 246 to run task
[2025-07-06T15:00:18.364+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'hello_world', 'hello_file_task', 'manual__2025-07-06T15:00:16.458026+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmprb3o_9zu']
[2025-07-06T15:00:18.366+0000] {standard_task_runner.py:85} INFO - Job 52: Subtask hello_file_task
[2025-07-06T15:00:18.378+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T15:00:18.407+0000] {task_command.py:410} INFO - Running <TaskInstance: hello_world.hello_file_task manual__2025-07-06T15:00:16.458026+00:00 [running]> on host 68809b9f89f0
[2025-07-06T15:00:18.474+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ds_const@mail.ru' AIRFLOW_CTX_DAG_OWNER='Daniil' AIRFLOW_CTX_DAG_ID='hello_world' AIRFLOW_CTX_TASK_ID='hello_file_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T15:00:16.458026+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T15:00:16.458026+00:00'
[2025-07-06T15:00:18.475+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-06T15:00:18.475+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sh /opt/***/dags/scripts/test.sh']
[2025-07-06T15:00:18.491+0000] {subprocess.py:86} INFO - Output:
[2025-07-06T15:00:18.492+0000] {subprocess.py:93} INFO - sh: 0: cannot open /opt/***/dags/scripts/test.sh: No such file
[2025-07-06T15:00:18.493+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-07-06T15:00:18.502+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-07-06T15:00:18.504+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=hello_world, task_id=hello_file_task, execution_date=20250706T150016, start_date=20250706T150018, end_date=20250706T150018
[2025-07-06T15:00:18.515+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 52 for task hello_file_task (Bash command failed. The command returned a non-zero exit code 2.; 246)
[2025-07-06T15:00:18.536+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-06T15:00:18.556+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
