[2025-07-06T11:12:37.936+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world.hello_file_task manual__2025-07-06T11:12:35.666796+00:00 [queued]>
[2025-07-06T11:12:37.942+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world.hello_file_task manual__2025-07-06T11:12:35.666796+00:00 [queued]>
[2025-07-06T11:12:37.942+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-07-06T11:12:37.954+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): hello_file_task> on 2025-07-06 11:12:35.666796+00:00
[2025-07-06T11:12:37.962+0000] {standard_task_runner.py:57} INFO - Started process 236 to run task
[2025-07-06T11:12:37.964+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'hello_world', 'hello_file_task', 'manual__2025-07-06T11:12:35.666796+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpe9veukdm']
[2025-07-06T11:12:37.965+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask hello_file_task
[2025-07-06T11:12:37.978+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T11:12:38.005+0000] {task_command.py:410} INFO - Running <TaskInstance: hello_world.hello_file_task manual__2025-07-06T11:12:35.666796+00:00 [running]> on host 3c708a467488
[2025-07-06T11:12:38.068+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hello_world' AIRFLOW_CTX_TASK_ID='hello_file_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T11:12:35.666796+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T11:12:35.666796+00:00'
[2025-07-06T11:12:38.069+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-06T11:12:38.069+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sh /home/alex/s6.sh ']
[2025-07-06T11:12:38.084+0000] {subprocess.py:86} INFO - Output:
[2025-07-06T11:12:38.086+0000] {subprocess.py:93} INFO - sh: 0: cannot open /home/alex/s6.sh: No such file
[2025-07-06T11:12:38.087+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-07-06T11:12:38.096+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-07-06T11:12:38.098+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=hello_world, task_id=hello_file_task, execution_date=20250706T111235, start_date=20250706T111237, end_date=20250706T111238
[2025-07-06T11:12:38.109+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 17 for task hello_file_task (Bash command failed. The command returned a non-zero exit code 2.; 236)
[2025-07-06T11:12:38.135+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-06T11:12:38.160+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
