[2025-07-06T19:04:03.778+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_activity_analysis.load_data manual__2025-07-06T18:58:58.367058+00:00 [queued]>
[2025-07-06T19:04:03.785+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_activity_analysis.load_data manual__2025-07-06T18:58:58.367058+00:00 [queued]>
[2025-07-06T19:04:03.785+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-07-06T19:04:03.797+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_data> on 2025-07-06 18:58:58.367058+00:00
[2025-07-06T19:04:03.806+0000] {standard_task_runner.py:57} INFO - Started process 780 to run task
[2025-07-06T19:04:03.810+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_activity_analysis', 'load_data', 'manual__2025-07-06T18:58:58.367058+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/customer_activity_dag.py', '--cfg-path', '/tmp/tmp4ucks9m_']
[2025-07-06T19:04:03.811+0000] {standard_task_runner.py:85} INFO - Job 74: Subtask load_data
[2025-07-06T19:04:03.825+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T19:04:03.855+0000] {task_command.py:410} INFO - Running <TaskInstance: customer_activity_analysis.load_data manual__2025-07-06T18:58:58.367058+00:00 [running]> on host 636fb1e40b9e
[2025-07-06T19:04:03.925+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ds_const@mail.ru' AIRFLOW_CTX_DAG_OWNER='Daniil' AIRFLOW_CTX_DAG_ID='customer_activity_analysis' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T18:58:58.367058+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T18:58:58.367058+00:00'
[2025-07-06T19:04:03.949+0000] {logging_mixin.py:150} INFO - Error in load_data: Expected a path-like, list of path-likes or a list of Datasets instead of the given type: NoneType
[2025-07-06T19:04:03.949+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/customer_activity_dag.py", line 130, in load_data
    new_data = pd.read_parquet(tmp_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 500, in read_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 240, in read
    path_or_handle, columns=columns, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet/core.py", line 2939, in read_table
    thrift_container_size_limit=thrift_container_size_limit,
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet/core.py", line 2480, in __init__
    ignore_prefixes=ignore_prefixes)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/dataset.py", line 784, in dataset
    'instead of the given type: {}'.format(type(source).__name__)
TypeError: Expected a path-like, list of path-likes or a list of Datasets instead of the given type: NoneType
[2025-07-06T19:04:03.957+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=customer_activity_analysis, task_id=load_data, execution_date=20250706T185858, start_date=20250706T190403, end_date=20250706T190403
[2025-07-06T19:04:03.968+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 74 for task load_data (Expected a path-like, list of path-likes or a list of Datasets instead of the given type: NoneType; 780)
[2025-07-06T19:04:03.981+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-06T19:04:03.997+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
